// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfyY1AsdjAjD-kgPthmqiUKv-bqOjTO9w',
    appId: '1:479367727007:web:76da86aa3bbe48b8e9dfaa',
    messagingSenderId: '479367727007',
    projectId: 'road-safety-ap',
    authDomain: 'road-safety-ap.firebaseapp.com',
    storageBucket: 'road-safety-ap.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH2f-ZIfjDDkBUaYCBnkyWCbz1Mv7D3Gk',
    appId: '1:479367727007:android:29075d65c2025722e9dfaa',
    messagingSenderId: '479367727007',
    projectId: 'road-safety-ap',
    storageBucket: 'road-safety-ap.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA9RwCjIpQmyaY_1QiOngwXC4JCbCP4NA',
    appId: '1:479367727007:ios:8444545ae90781e8e9dfaa',
    messagingSenderId: '479367727007',
    projectId: 'road-safety-ap',
    storageBucket: 'road-safety-ap.appspot.com',
    iosBundleId: 'com.example.roadSafetyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA9RwCjIpQmyaY_1QiOngwXC4JCbCP4NA',
    appId: '1:479367727007:ios:75e83bbd4c8e10a4e9dfaa',
    messagingSenderId: '479367727007',
    projectId: 'road-safety-ap',
    storageBucket: 'road-safety-ap.appspot.com',
    iosBundleId: 'com.example.roadSafetyApp.RunnerTests',
  );
}
